### PR TITLE
Add study page

### PR DESCRIPTION
**Pull request by Elkrival**
* added studies page

@mikestone14 I've noticed that the icons available from material are different than what's in figma. Where do we get the right ones..? might Berfin own them..?

Figma
Screenshot 2024-03-29 at 1 31 00 PM

Material
Screenshot 2024-03-29 at 1 32 45 PM

### CODE REVIEW

**Review by mikestone14 — COMMENTED** [review]
This looks good to me. Until we have the rest of the page built out, let's merge this into a long-running feature branch and move the tickets to the limbo state so we don't deploy an empty page.

**Review by mikestone14 — COMMENTED** [review]
Should we also have a test for this page? Not sure if we have page level tests in the app yet.

**Comment by JackVCurtis** [comment]
> Should we also have a test for this page? Not sure if we have page level tests in the app yet.

We do have page tests, but they're pretty basic right now. E.g. testing that the page renders rather than testing dynamic behavior on the page.

**Comment by Elkrival** [comment]
> Should we also have a test for this page? Not sure if we have page level tests in the app yet.

We have some... this is the diff for this one https://github.com/AMP-SCZ/dpdash/pull/718/files#diff-f53cd4dd7b90bcad02763df5dd2790d149c0012245ec6066103f50f113ffe6f1

**Review by mikestone14 — APPROVED** [review]

**Pull request merged**
