### PR TITLE
Changes required for multi-user, same-machine instances

### PR DESCRIPTION
**Pull request by tashrifbillah**
(No need to merge anytime soon)

Use branch `multi-user-config` to run an independent instance of DPDash in the `rc-predict` VM

With the changes in effect, `init.sh` should complete successfully. Then, it gets stuck at [Run](https://github.com/PREDICT-DPACC/dpdash/blob/pnl-devel/README-PNL.md#run), more specifically at [npm start](https://github.com/PREDICT-DPACC/dpdash/blob/pnl-devel/singularity/run.sh#L39):

```sh
Singularity> npm start
> po@0.0.0 start /sw/apps/dpdash
> NODE_ENV=production ./node_modules/pm2/bin/pm2 start bin/www

[PM2][ERROR] Script already launched, add -f option to force re-execution
```

Obviously, the reason is that another `www` is running there since time immemorial. @blms may be able to help with devising a proper `npm` command for launching a separate node app that uses the same [bin/www](https://github.com/PREDICT-DPACC/dpdash/blob/pnl-devel/bin/www)

### CODE REVIEW

**Comment by blms** [comment]
Thanks for your work getting this further along Tashrif! I’ll give it a try shortly and see if I can solve the node issue.

**Comment by blms** [comment]
Actually had no problem running the same script—it just worked!

```sh
> po@0.0.0 start /sw/apps/dpdash
> NODE_ENV=production ./node_modules/pm2/bin/pm2 start bin/www

[PM2] Starting /sw/apps/dpdash/bin/www in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬─────────┬──────┬────────┬────────┬─────────┬────────┬─────┬───────────┬───────┬──────────┐
│ App name │ id │ version │ mode │ pid    │ status │ restart │ uptime │ cpu │ mem       │ user  │ watching │
├──────────┼────┼─────────┼──────┼────────┼────────┼─────────┼────────┼─────┼───────────┼───────┼──────────┤
│ www      │ 0  │ 0.0.0   │ fork │ 106070 │ online │ 0       │ 0s     │ 0%  │ 16.9 MB   │ bls64 │ disabled │
└──────────┴────┴─────────┴──────┴────────┴────────┴─────────┴────────┴─────┴───────────┴───────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

I did have to change all of the ports again. I guess some of the ones you specified above are being used now? (Mongo gave me the old "port in use" error code so I just incremented all ports again.) But that's fine because this PR shows exactly where they need to be changed! 😃

**Comment by tashrifbillah** [comment]
> Actually had no problem running the same script—it just worked!

Then I think it was a problem for the same user. But that is okay, I wouldn't need to run two independent DPDash instances.

>  I guess some of the ones you specified above are being used now?

I closed all my trials around the same time I invited you.

If you have been successful, I should be able to see the following:

```sh
[tb571@rc-predict singularity]$ curl -L http://localhost:8001
curl: (7) Failed connect to localhost:8001; Connection refused
```

Did you verify that? Are you using a different port than `8001`?

**Comment by blms** [comment]
>Did you verify that? Are you using a different port than 8001?

Yes, I'm using 8002, from when I incremented all ports. Verified that `curl`ing `localhost:8002` works.

>I closed all my trials around the same time I invited you.

Strange. Maybe it's only MongoDB holding onto that port for some reason.

**Comment by tashrifbillah** [comment]
All right, `curl -L http://localhost:8002` works. The day's been a success, now you have a way to play with it independently 🗡️

**Comment by blms** [comment]
Sure, I'll work on that in #10. It does indeed look like that config file is being ignored.

In the meantime, here is a result of running the `quit.sh` script in the case of multi-user instances of dpdash.

<details>

  <summary>quit.sh output</summary>

```sh
Singularity> ./quit.sh

> po@0.0.0 stop /sw/apps/dpdash
> ./node_modules/pm2/bin/pm2 stop all && ./node_modules/pm2/bin/pm2 delete all

[PM2] Applying action stopProcessId on app [all](ids: 0)
[PM2] [www](0) ✓
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬───────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user  │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼───────┼──────────┤
│ www      │ 0  │ 0.0.0   │ fork │ 0   │ stopped │ 0       │ 0      │ 0%  │ 0 B    │ bls64 │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴───────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[PM2] Applying action deleteProcessId on app [all](ids: 0)
[PM2] [www](0) ✓
┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
pkill: killing pid 10326 failed: Operation not permitted
pkill: killing pid 7679 failed: Operation not permitted
pkill: killing pid 7824 failed: Operation not permitted
pkill: killing pid 8234 failed: Operation not permitted
pkill: killing pid 8022 failed: Operation not permitted
pkill: killing pid 8234 failed: Operation not permitted
pkill: killing pid 7826 failed: Operation not permitted
pkill: killing pid 9019 failed: Operation not permitted
pkill: killing pid 7813 failed: Operation not permitted
```

</details>

It may not be a problem at all, since it does correctly stop the app from running, and the processes that it fails to kill seem to have correct permissions (i.e. I am not, and should not be, permitted to kill them). But I thought it's worth posting here, especially in the event that it _does_ kill a process it shouldn't be killing.

<details>
<summary>ps output</summary>

```sh
Singularity> ps u -ww 7679 7813 7824 7826 8022 8234 9019 10326
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
4414294    7679  0.0  0.4  40836 16540 ?        Ss   Apr14   3:29 /sw/apps/miniconda3/bin/python /sw/apps/miniconda3/bin/supervisord -c /data/dpdash/configs/supervisord.conf
4414294    7813  0.6  2.3 1020124 91464 ?       Sl   Apr14  73:20 mongod --config /data/dpdash/configs/mongodb.conf --logpath /data/dpdash/mongodb/logs/mongod.log
4414294    7824  0.0  0.0  11172  1532 ?        S    Apr14   0:00 /bin/sh -e /usr/lib/rabbitmq/bin/rabbitmq-server
4414294    7826  0.1  1.4 278624 56372 ?        S    Apr14  15:26 /sw/apps/miniconda3/bin/python /sw/apps/miniconda3/bin/celery worker -A dppy -l info -E -f /data/dpdash/celery/celery.log -Q dpdash -Ofair --pidfile /data/dpdash/celery/celeryd.pid
4414294    8022  0.0  0.0  11628   324 ?        S    Apr14   0:09 /usr/lib64/erlang/erts-8.3.5.7/bin/epmd -daemon
4414294    8234  0.1  1.5 2216692 59848 ?       Sl   Apr14  15:57 /usr/lib64/erlang/erts-8.3.5.7/bin/beam -W w -A 64 -P 1048576 -t 5000000 -stbt db -zdbbl 32000 -K true -B i -- -root /usr/lib64/erlang -progname erl -- -home /home/tb571 -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/ebin -noshell -noinput -s rabbit boot -sname rabbit@rc-predict -boot start_sasl -config /data/dpdash/configs/rabbitmq -kernel inet_default_connect_options [{nodelay,true}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_logger {file,"/data/dpdash/rabbitmq/rabbit@rc-predict.log"} -rabbit sasl_error_logger {file,"/data/dpdash/rabbitmq/rabbit@rc-predict-sasl.log"} -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/lib/rabbitmq/plugins:/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/plugins" -rabbit plugins_expand_dir "/data/dpdash/rabbitmq/rabbit@rc-predict-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/data/dpdash/rabbitmq/rabbit@rc-predict" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
4414294    9019  0.0  1.5 410904 58320 ?        S    Apr14   0:01 /sw/apps/miniconda3/bin/python /sw/apps/miniconda3/bin/celery worker -A dppy -l info -E -f /data/dpdash/celery/celery.log -Q dpdash -Ofair --pidfile /data/dpdash/celery/celeryd.pid
4414294   10326  0.0  1.3 1200388 52056 ?       Ssl  Apr14   6:03 PM2 v3.2.2: God Daemon (/home/tb571/.pm2)
```

</details>

**Comment by tashrifbillah** [comment]
Failed ones are all my processes so the failure is expected. I am not sure why `4414294` did not resolve to `tb571`.

Anyways, you can brainstorm on making `quit.sh` contained commands kill only user-owned processes. We have a [TODO](https://github.com/PREDICT-DPACC/dpdash/blob/pnl-devel/singularity/quit.sh#L10) marked regarding this already.

**Comment by blms** [comment]
BTW, I'm going to work off this branch for now on #10 so that I have all of your related commits while I work on it.

After I finish #10, I would like to make this PR mergeable into `pnl-devel` by making all of these ports and stuff configurable externally from the scripts, maybe in an `.env` file, and then load them into the scripts from there. Does that make sense? I'll update documentation for this of course.

(In doing so, I'll also revert the defaults to their original values, and only override them if they are present in `.env`.)

**Comment by tashrifbillah** [comment]
As long as they are configurable externally, it should be fine.

**Comment by blms** [comment]
This should now be mergeable too 🙂

**Pull request merged**
