### PR TITLE
add endpoint to delete assessmentDayData (already exists for metadata)

### PR DESCRIPTION
**Pull request by JackVCurtis**

### CODE REVIEW

**Review by Elkrival — APPROVED** [review]
This looks good, am I adding this to the importer script..?

**Review by mikestone14 — COMMENTED** [review]
why do we want to drop the entire collection? Are there concerns that someone could make a request from the app to drop the collection?

**Comment by Elkrival** [comment]
I think that we want to reimport the data with the new updates that were done to both the metadata and assessmentDayData collection

**Comment by JackVCurtis** [comment]
> This looks good, am I adding this to the importer script..?

I don't think so, when we need to use this endpoint we can just use a simple curl request: 

```bash
curl -H "x-api-user: importer" -H "x-api-key: super_secret" -X DELETE localhost:8000/api/v1/import/data/day
```

**Comment by JackVCurtis** [comment]
> why do we want to drop the entire collection? Are there concerns that someone could make a request from the app to drop the collection?

We want to drop the collection because we don't have any other way to remove a number of duplicate documents that crept into staging somehow. Justin is also looking to use a slightly more prod-like data set. You can check out [this thread](https://gnardog.slack.com/archives/C03KGHSSTNC/p1710424204490899) in Slack for the details.

As to the second point, there's no way for a regular user to drop the collection. This endpoint is only accessible if you have the API key we use to import data, it's a separate authentication setup from the cookie-based auth we use for the app-facing API.

**Comment by mikestone14** [comment]
Got it. That makes sense, thanks for the explanation!

**Pull request merged**
