### PR TITLE
add user to dependency array for re-rendering graph

### LINKED ISSUE #693: Matrix page fails to update the matrix when a new configuration is selected

### PR DESCRIPTION
**Pull request by JackVCurtis**
Fixes https://github.com/AMP-SCZ/dpdash/issues/693

### CODE REVIEW

**Comment by Elkrival** [comment]
Ran this locally, are all the commits present..?   I still get errors and the main issue isn't fixed.
https://drive.google.com/file/d/1Dz5humZroCLRZ7t4cSYwLQxvgUT3Gzet/view?usp=sharing

**Comment by Elkrival** [comment]
is this a draft pr..?

**Comment by JackVCurtis** [comment]
Sorry, I accidentally committed a file that I had to patch because of some mongo behavior that's happening for me locally. That broke the ability to change the config. The current commits should fix the issue you demoed.

**Comment by Elkrival** [comment]
onMount is being called in one useEffect and renderMatrix is called in another, they both have tracking dependencies, and I'm curious if we need the useEffect with renderMatrix, because that function is being executed inside the onMount function

```javascript
  const onMount = async () => {
    try {
      const graphData = await fetchGraph()

      setGraph(graphData.graph)
      updateMaxDay(graphData.graph)
      renderMatrix(graphData.graph)
```

**Comment by JackVCurtis** [comment]
> onMount is being called in one useEffect and renderMatrix is called in another, they both have tracking dependencies, and I'm curious if we need the useEffect with renderMatrix, because that function is being executed inside the onMount function
> 
> ```js
>   const onMount = async () => {
>     try {
>       const graphData = await fetchGraph()
> 
>       setGraph(graphData.graph)
>       updateMaxDay(graphData.graph)
>       renderMatrix(graphData.graph)
> ```

Took another look and tested it out. If we remove the bottom `useEffect` the graph fails to render, but we can remove the call to `renderMatrix` in the first `useEffect` because it's 1. redundant and 2. causing the `svg` error notification

**Comment by JackVCurtis** [comment]
Threw in #694 [b29be9b](https://github.com/AMP-SCZ/dpdash/pull/714/commits/b29be9ba3ae46637f7d716c85ed72a9b12f6156d)

**Review by mikestone14 — APPROVED** [review]

**Comment by justintbaker** [comment]
This still doesn't work as expected.  There is a lag where you switch to a different configuration (N) and only the N-1 selected configuration shows.   

image
image
image
image

**Pull request merged**
