### PR TITLE
Move Javascript build to public build

### PR DESCRIPTION
**Pull request by Elkrival**
This pr moves the javascript build from app_build to the public directory.
Places that loaded app_build are now loaded to public. During the build process webpack removes the assests. This adds the copy plugin the files that are removed into the public directory. We need the template because webpack does not create a react template index.html file.
For singularity the app_build was returned back to public.

### CODE REVIEW

**Comment by taylorkearns** [comment]
> This adds the copy plugin the files that are removed into the public directory

Sorry I'm unclear on what this means?

Also can you add some info about why we are making these changes?

**Review by taylorkearns — APPROVED** [review]

**Comment by taylorkearns** [comment]
Is `app_build` compiled at build time when the app is deployed or is it packaged up when it sends to the front end? I'm wondering if we are "publicizing" any files that were previously private and need to stay that way?

**Comment by Elkrival** [comment]
@taylorkearns when webpack builds the application it replaces the files in the build directory. The copy plugin it moves the files from one directory to another. We are doing this because the folder app_build does not have enough permissions in the container to run it's commands, and the person who handles the deploys does not want to give permissions to launch from the directory so instead they want us to put it in the public directory.

**Comment by Elkrival** [comment]
> Is `app_build` compiled at build time when the app is deployed or is it packaged up when it sends to the front end? I'm wondering if we are "publicizing" any files that were previously private and need to stay that way?

Yes the appbuild is happening at build time

**Pull request merged**
